### PR TITLE
Maquiagem para os notebooks e README

### PR DESCRIPTION
**Pull request by leouieda**
@birocoles dei uma arrumada nos notebooks e coloquei mais coisa no README baseado no do [paper-tesseroids](https://github.com/pinga-lab/paper-tesseroids).

Pode ver os notebooks no nbviewer: http://nbviewer.ipython.org/github/pinga-lab/Total-magnetization-of-spherical-bodies/tree/maquiagem/notebooks/

E o README: https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/blob/maquiagem/README.md

Se tiver OK pode apertar o merge. Vou fazer as mudanças no texto em outro branch.

### CODE REVIEW

**Comment by birocoles** [comment]
Cara,

To indo pra casa. Vou ver isso de lá.

Abraço

On Thu, Mar 19, 2015 at 4:50 PM, Leonardo Uieda <notifications@github.com>
wrote:

> @birocoles <https://github.com/birocoles> dei uma arrumada nos notebooks
> e coloquei mais coisa no README baseado no do paper-tesseroids
> <https://github.com/pinga-lab/paper-tesseroids>.
>
> Pode ver os notebooks no nbviewer:
> http://nbviewer.ipython.org/github/pinga-lab/Total-magnetization-of-spherical-bodies/tree/maquiagem/notebooks/
>
> E o README:
> https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/blob/maquiagem/README.md
>
> Se tiver OK pode apertar o merge. Vou fazer as mudanças no texto em outro
> branch.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>
> https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15
> Commit Summary
>
>    - Add a header and some text to all notebooks
>    - Added more instructions and information to README
>
> File Changes
>
>    - *M* README.md
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-0>
>    (149)
>    - *M* notebooks/real_data/GoiasAlkalineProvince.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-1>
>    (13170)
>    - *M* notebooks/suppl_tests/additional_tests/synthetic_tests-L1.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-2>
>    (63)
>    - *M* notebooks/suppl_tests/additional_tests/synthetic_tests-L2.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-3>
>    (24811)
>    - *M*
>    notebooks/suppl_tests/comparison_sphere_cube/synthetic_tests_sphere_prism.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-4>
>    (8011)
>    - *M* notebooks/suppl_tests/complex/complex_test.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-5>
>    (6)
>    - *M* notebooks/synthetic_tests/synthetic_tests_centre_error.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-6>
>    (1508)
>    - *M*
>    notebooks/synthetic_tests/synthetic_tests_interfering_anomaly.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-7>
>    (5471)
>    - *M* notebooks/synthetic_tests/synthetic_tests_shape_robustness.ipynb
>    <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15/files#diff-8>
>    (5476)
>
> Patch Links:
>
>    -
>    https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15.patch
>    -
>    https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pinga-lab/Total-magnetization-of-spherical-bodies/pull/15>
> .
>



-- 
--------------------------------------------------------------------------
VANDERLEI C. OLIVEIRA JR. <http://fatiando.org/people/oliveira-jr/>
Pesquisador
Coordenação de Geofísica - COGE
Observatório Nacional / MCTI
Rua General Jose Cristino 77
20921-400, Rio de Janeiro, RJ
Prédio Lélio I. Gama, Sala 304
Email: vanderlei@on.br / vandscoelho@gmail.com
Fone: (21) 3504 9115
--------------------------------------------------------------------------

Antes de imprimir, pense em sua responsabilidade com o meio ambiente.
Before printing, think about your responsibility with the environment.

**Comment by birocoles** [comment]
@leouieda, ficou muito da hora. Vou dar o merge

**Comment by birocoles** [comment]
@leouieda, ao mergir as modificações nos notebooks, alguns links irão quebrar, não vão?

**Comment by leouieda** [comment]
Não, os links do README  já são do master

**Pull request merged**
